Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

(For : Q1 and Q2)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [11]:
import numpy as np

list_ = ['1','2','3','4','5']  #It is List Object

array_list = np.array(object = list_) ##It is a Numpy Array

""" List:General-purpose dynamic array for storing elements of any type, supporting
          dynamic resizing.
    NumPy:Numerical computing library with efficient multidimensional arrays, optimized 
         for numerical operations and homogeneous data types, providing extensive mathematical
         functionality.
"""

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
for i in iter(list_):
    print(i,"Element of list_:",type(i))
    
for j in iter(array_list):
    print(j,"Element of list_:",type(j))    
    
""" the data type of each element in array_list is numpy.str_, 
    which is a specific string data type used by NumPy arrays."""    

1 Element of list_: <class 'str'>
2 Element of list_: <class 'str'>
3 Element of list_: <class 'str'>
4 Element of list_: <class 'str'>
5 Element of list_: <class 'str'>
1 Element of list_: <class 'numpy.str_'>
2 Element of list_: <class 'numpy.str_'>
3 Element of list_: <class 'numpy.str_'>
4 Element of list_: <class 'numpy.str_'>
5 Element of list_: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.



In [16]:
array_list = np.array(object = list_, dtype = int)
for i in iter(array_list):
    print(i,"Element of list_:",type(j))    
    
""" data type of each element in the updated array_list is now numpy.int64, 
    indicating integers. The elements in list_ still retain their original 
    data type, which is str. """   

1 Element of list_: <class 'numpy.int64'>
2 Element of list_: <class 'numpy.int64'>
3 Element of list_: <class 'numpy.int64'>
4 Element of list_: <class 'numpy.int64'>
5 Element of list_: <class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [21]:
num_list =[[1,2,3],[4,5,6]]
num_array=np.array(num_list)
print("Shape of an array : ",num_array.shape)
print("Size of an array : ",num_array.size)

Shape of an array :  (2, 3)
Size of an array :  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [26]:
zero_array=np.zeros((3,3))
print(zero_array)
print("Shape of an array : ",zero_array.shape)
print("Size of an array : ",zero_array.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape of an array :  (3, 3)
Size of an array :  9


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [28]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])